Feature releases (#57)
* Allow aws:elasticbeanstalk:managedactions toggling

* Remove duplicate DeploymentPolicy setting

* Add support for CloudWatch health log streaming

* Updated documentation

* Rebuild README

* Add all beanstalk outputs

* Documentation updates

* Add description variable and fix for boolean values

* Remove description output

It is listed in the documentation but fails every time. It isn’t a critical output anyway.

Error: Error running plan: 1 error(s) occurred:

* module.elastic_beanstalk_environment.output.description: Resource 'aws_elastic_beanstalk_environment.default' does not have attribute 'description' for variable 'aws_elastic_beanstalk_environment.default.description'

* Documentation update

* Updated enable_managed_actions documentation

* tf fmt